name: l10n_decompose
description: This CLI generate decomposed localization by different directories for each feature.
version: 0.1.0
repository: https://github.com/AndreyKedo/l10n_decompose

workspace: 
  - example

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  meta: any
  logging: 1.3.0
  ansi_styles: ^0.3.2+1
  args: ^2.7.0
  path: ^1.9.1
  yaml: ^3.1.3


dev_dependencies:
  lints: any
  test: any
